name = "pm-print-standalone"
main = "src/worker.js"
compatibility_date = "2026-08-30"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pmprint-db"
database_id = "e7975f99-c0cb-4667-85b9-f85673b96a17"
migrations_dir = "migrations"
migrations_table = "d1_migrations_pm"

[[r2_buckets]]
binding = "PRINT_FILES"
bucket_name = "pm-print"

[vars]
PM_APP_NAME = "PM PRINT"
MAX_UPLOAD_BYTES = "20971520"
